// 主进程与预加载层共享 IPC 通道，避免字符串分散后发生拼写漂移。
const ipcTongdao = Object.freeze({
  getSystemStatus: 'system:read-status',
  getAppInfo: 'app:read-info',
  checkAppUpdate: 'app:check-update',
  openAppRelease: 'app:open-release',
  appUpdateInfoChanged: 'app:update-info-changed',
  setAutoLaunch: 'app:set-auto-launch',
  setIslandPassthrough: 'island:set-passthrough',
  setFloatingMode: 'island:set-floating-mode',
  floatingWindowShown: 'floating:shown',
  moveFloatingIsland: 'island:move-floating',
  completeStartup: 'island:startup-complete',
  setHeavyTasksPaused: 'island:set-heavy-tasks-paused',
  selectLibraryRootdir: 'library:select-rootdir',
  getLibraryConfig: 'library:read-config',
  getCollapsedAnimation: 'settings:read-collapsed-animation',
  setCollapsedAnimation: 'settings:set-collapsed-animation',
  importLibraryContent: 'library:import',
  captureClipboardContent: 'library:capture-clipboard',
  tongbuDesktopApplications: 'applications:sync-desktop',
  getLibrarySummary: 'library:read-summary',
  libraryChanged: 'library:changed',
  getLibraryPage: 'library:read-page',
  searchLibrary: 'library:search',
  getApplicationIcons: 'library:read-application-icons',
  getWebsiteIcons: 'library:read-website-icons',
  getImageThumbnails: 'library:read-image-thumbnails',
  openLibraryItem: 'library:open-item',
  locateLibraryItem: 'library:locate-item',
  renameLibraryItem: 'library:rename-item',
  deleteLibraryItem: 'library:delete-item',
  shareLibraryItem: 'library:share-item',
})

module.exports = { ipcTongdao }
